project_id = "pqtywzpgxpkkunkgsocy"

[functions.generate-story-part-1]
verify_jwt = true

[functions.generate-story-part-2]
verify_jwt = true

[functions.generate-story-part-3]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.merge-style-prompt]
verify_jwt = false

[functions.augment-character-sheet]
verify_jwt = true
