project_id = "pqtywzpgxpkkunkgsocy"

[functions.generate-story-part-1]
verify_jwt = true

[functions.generate-story-part-2]
verify_jwt = true

[functions.generate-story-part-3]
verify_jwt = true

[functions.generate-story-image]
verify_jwt = true

[functions.generate-story-image-leonardo]
verify_jwt = true

[functions.generate-story-audio]
verify_jwt = true

[functions.generate-story-pdf]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.merge-style-prompt]
verify_jwt = false