project_id = "pqtywzpgxpkkunkgsocy"

[functions.generate-story]
verify_jwt = true

[functions.generate-story-image]
verify_jwt = true

[functions.generate-story-audio]
verify_jwt = true

[functions.generate-story-pdf]
verify_jwt = true